### ISSUE TITLE
how to download vila weights

### ISSUE THREAD

**Issue by msaoudallah** [allenai/mmda#280]
i'm trying to use section nesting example , but i'm getting this error 
```
$ python examples/section_nesting_prediction/main.py
Traceback (most recent call last):
  File "D:\CARDs\segmentation v10\mmda\mmda\examples\section_nesting_prediction\main.py", line 91, in <module>
    main()
  File "D:\CARDs\segmentation v10\mmda\mmda\examples\section_nesting_prediction\main.py", line 28, in main
    layout_predictor = LayoutParserPredictor.from_pretrained(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\synth\anaconda3\Lib\site-packages\mmda\predictors\lp_predictors.py", line 34, in from_pretrained
    model = lp.AutoLayoutModel(
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\synth\anaconda3\Lib\site-packages\layoutparser\models\auto_layoutmodel.py", line 64, in AutoLayoutModel
    return ALL_AVAILABLE_BACKENDS[backend_name](
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\synth\anaconda3\Lib\site-packages\layoutparser\models\effdet\layoutmodel.py", line 138, in __init__
    self._initialize_model(config_path, model_path, label_map, extra_config)
  File "C:\Users\synth\anaconda3\Lib\site-packages\layoutparser\models\effdet\layoutmodel.py", line 164, in _initialize_model
    model_path = PathManager.get_local_path(model_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\synth\anaconda3\Lib\site-packages\iopath\common\file_io.py", line 1251, in get_local_path
    bret = handler._get_local_path(path, force=force, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\synth\anaconda3\Lib\site-packages\layoutparser\models\effdet\catalog.py", line 64, in _get_local_path
    return PathManager.get_local_path(model_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\synth\anaconda3\Lib\site-packages\iopath\common\file_io.py", line 1251, in get_local_path
    bret = handler._get_local_path(path, force=force, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\synth\anaconda3\Lib\site-packages\iopath\common\file_io.py", line 835, in _get_local_path
    with file_lock(cached):
  File "C:\Users\synth\anaconda3\Lib\site-packages\portalocker\utils.py", line 163, in __enter__
    return self.acquire()
           ^^^^^^^^^^^^^^
  File "C:\Users\synth\anaconda3\Lib\site-packages\portalocker\utils.py", line 258, in acquire
    fh = self._get_fh()
         ^^^^^^^^^^^^^^
  File "C:\Users\synth\anaconda3\Lib\site-packages\portalocker\utils.py", line 307, in _get_fh
    return open(  # noqa: SIM115
           ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\synth/.torch/iopath_cache\\s/ukbw5s673633hsw\\publaynet-tf_efficientdet_d0.pth.tar?dl=1.lock'
```

i saw that in this readme https://github.com/allenai/mmda/tree/main/examples/vila_for_scidoc_parsing#installation you mention to contact @shannons , but i can't find this contributor anywhere :]

**Comment by soldni** [comment]
@lolipopshock any suggestion on how to improve instructions here?
